arch = "AArch64"
name = "CoTWinv"
symbolic = ["x"]

page_table_setup = """
    physical pa1;
    x |-> pa1;
    x ?-> invalid;
    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    LDR X0,[X1]
    STR X2,[X3]
"""

[thread.0.reset]
R1 = "x"
R2 = "extz(0b0, 64)"
R3 = "pte3(x, page_table_base)"

VBAR_EL1 = "extz(0x1000, 64)"

"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[section.thread0_el1_handler]
address = "0x1400"
code = """
    MOV X0,#1

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
expect = "sat"
assertion = "0:X0 = 1"
