arch = "AArch64"
name = "CoWinvTv2.2+dsb-tlbivmidis-msrvttbr-dsb-eret"
symbolic = ["x"]

page_table_setup = """
    physical pa1;
    intermediate ipa1;

    x |-> ipa1;
    ipa1 |-> pa1;
    ipa1 ?-> invalid;

    *pa1 = 0;
    identity 0x2000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
    DSB SY
    TLBI VMALLS12E1IS
    DSB SY
    MSR VTTBR_EL2,X4
    ERET
L0:
    LDR X2,[X3]
"""

[thread.0.reset]
R0 = "extz(0b0, 64)"
R1 = "pte3(ipa1, s2_page_table_base)"
R3 = "x"
R4 = "ttbr(vmid=0x0001, base=s2_page_table_base)"
VBAR_EL2 = "extz(0x2000, 64)"

"PSTATE.EL" = "0b10"

# return to EL1t at L0
SPSR_EL2 = "extz(0b00101, 64)"
ELR_EL2 = "L0:"

[section.thread0_el2_handler]
address = "0x2400"  # +0x400 -> Exception from Lower Exception Level
code = """
    MOV X2,#1
"""

[final]
assertion = "0:X2 = 0"
