arch = "AArch64"
name = "CoWTf.inv+rfi-addr"
symbolic = ["x", "y"]

page_table_setup = """
    physical pa1;
    x |-> invalid;
    x ?-> pa1;
    y |-> pa1;
    *pa1 = 1;
    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
    LDR X2,[X3]
    LDR X4,[X5]
"""

[thread.0.reset]
R0 = "desc3(y, page_table_base)"
R1 = "pte3(x, page_table_base)"
R3 = "pte3(x, page_table_base)"
R5 = "x"
VBAR_EL1 = "extz(0x1000, 64)"

"PSTATE.SP" = "0b0"

[section.thread0_el1_handler]
address = "0x1400"
code = """
    MOV X4,#0

    MRS X20,ELR_EL1
    ADD X20,X20,#4
    MSR ELR_EL1,X20
    ERET
"""

[final]
expect = "sat"
assertion = "0:X2 = desc3(y, page_table_base) & 0:X4 = 0"
