arch = "AArch64"
name = "LB.TT.inv+pos"
symbolic = ["x", "y"]

page_table_setup = """
    physical pa1;
    x |-> invalid;
    y |-> invalid;

    x ?-> pa1;
    y ?-> pa1;

    *pa1 = 1;

    identity 0x1000 with code;
    identity 0x2000 with code;
"""

[thread.0]
init = {}
code = """
    LDR X0,[X1]
    STR X2,[X3]
"""

[thread.0.reset]
R1 = "x"
R2 = "mkdesc3(oa=pa1)"
R3 = "pte3(y, page_table_base)"
VBAR_EL1 = "extz(0x1000, 64)"
"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[section.thread0_el1_handler]
address = "0x1400"
code = """
    MOV X0,#0

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[thread.1]
init = {}
code = """
    LDR X0,[X1]
    STR X2,[X3]
"""

[thread.1.reset]
R1 = "y"
R2 = "mkdesc3(oa=pa1)"
R3 = "pte3(x, page_table_base)"
VBAR_EL1 = "extz(0x2000, 64)"
"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[section.thread1_el1_handler]
address = "0x1400"
code = """
    MOV X0,#0

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
assertion = "0:X0 = 1 & 1:X0=1"
