arch = "AArch64"
name = "MP.BBM1+dsb-tlbiis-dsb-dsb+dsb-isb"
symbolic = ["x", "y"]

page_table_setup = """
    physical pa1 pa2 pa3;
    x |-> pa1;
    x ?-> invalid;
    x ?-> pa2;

    y |-> pa3;
    identity 0x1000 with code;

    *pa2 = 1;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
    DSB SY
    TLBI VAE1IS,X6
    DSB SY
    STR X2,[X1]
    DSB SY
    STR X4,[X5]
"""

[thread.0.reset]
R0 = "extz(0b0, 64)"
R1 = "pte3(x, page_table_base)"
R2 = "mkdesc3(oa=pa2)"
R4 = "extz(0b1, 64)"
R5 = "y"
R6 = "extz(page(x), 64)"

"PSTATE.EL" = "0b01"

[thread.1]
init = {}
code = """
    LDR X0,[X1]
    DSB SY
    ISB
    LDR X2,[X3]
"""

[thread.1.reset]
R1 = "y"
R3 = "x"
VBAR_EL1 = "extz(0x1000, 64)"

"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[section.thread1_el1_handler]
address = "0x1400"
code = """
    MOV X2,#0

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
assertion = "1:X0=1 & 1:X2=0"
