arch = "AArch64"
name = "MP.RT.EL1+dsb+dsb-tlbiis-dsb+dsb+dsb-isb"
symbolic = ["x", "y", "z", "a"]

page_table_setup = """
    physical pa1 pa2 pa3;
    x |-> pa1;
    x ?-> invalid;

    y |-> pa2;

    a |-> pa3;
    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
    DSB SY
    STR X2,[X3]
"""

[thread.0.reset]
R0 = "extz(0b0, 64)"
R1 = "pte3(x, page_table_base)"
R2 = "extz(0x1, 64)"
R3 = "a"

"PSTATE.EL" = "0b01"

[thread.1]
init = {}
code = """
    LDR X0,[X1]
    DSB SY
    TLBI VAE1IS,X4
    DSB SY
    STR X2,[X3]
"""

[thread.1.reset]
R1 = "a"
R2 = "extz(0x2, 64)"
R3 = "a"
R4 = "extz(page(x), 64)"

"PSTATE.EL" = "0b01"

[thread.2]
init = {}
code = """
    LDR X0,[X1]
    DSB SY
    STR X2,[X3]
"""

[thread.2.reset]
R1 = "a"
R2 = "extz(0b1, 64)"
R3 = "y"

"PSTATE.EL" = "0b01"


[thread.3]
init = {}
code = """
    LDR X0,[X1]
    DSB SY
    ISB
    LDR X2,[X3]
"""

[thread.3.reset]
R1 = "y"
R3 = "x"
VBAR_EL1 = "extz(0x1000, 64)"

"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[section.thread3_el1_handler]
address = "0x1400"
code = """
    MOV X2,#1

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
expect = "sat"
assertion = "1:X0=1 & 2:X0=2 & 3:X0 = 1 & 3:X2=0"