arch = "AArch64"
name = "MP.TTf.inv.EL1+dsb-tlbiis-dsb+dmb"
symbolic = ["x", "y", "z"]

page_table_setup = """
    physical pa1 pa2;
    x |-> invalid;
    x ?-> pa1;

    y |-> invalid;
    y ?-> pa2;

    *pa1 = 1;
    *pa2 = 1;
    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
    DSB SY
    TLBI VAE1IS,X4
    DSB SY
    STR X2,[X3]
"""

[thread.0.reset]
R0 = "mkdesc3(oa=pa1)"
R1 = "pte3(x, page_table_base)"
R2 = "mkdesc3(oa=pa2)"
R3 = "pte3(y, page_table_base)"
R4 = "extz(page(x), 64)"

"PSTATE.EL" = "0b01"

[thread.1]
init = {}
code = """
    LDR X2,[X1]
    MOV X0,X2
    DMB SY
    LDR X2,[X3]
"""

[thread.1.reset]
R1 = "y"
R3 = "x"
VBAR_EL1 = "extz(0x1000, 64)"

"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[section.thread1_el1_handler]
address = "0x1400"
code = """
    MOV X2,#0

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
expect = "sat"
assertion = "1:X0 = 1 & 1:X2=0"