arch = "AArch64"
name = "RWC.RTR.EL1+dsb-isb+dsb-tlbi-dsb"
symbolic = ["x", "y", "z"]

page_table_setup = """
    physical pa1 pa2;
    x |-> pa1;

    y |-> pa2;
    y ?-> invalid;
    z |-> pa2;
    *pa1 = 1;

    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
"""

[thread.0.reset]
R0 = "extz(0b1, 64)"
R1 = "x"

"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[thread.1]
init = {}
code = """
    LDR X0,[X1]
    CBNZ X0,L0
L0:
    ISB
    LDR X3,[X4,X2]
"""

[thread.1.reset]
R1 = "x"
R3 = "extz(0b1, 64)"
R4 = "y"

VBAR_EL1 = "extz(0x2000, 64)"
"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[section.thread1_el1_handler]
address = "0x1400"
code = """
    MOV X3,#0

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[thread.2]
init = {}
code = """
    STR X0,[X1]
    DSB SY
    TLBI VAE1IS,X2
    DSB SY
    LDR X3,[X4]
"""

[thread.2.reset]
R0 = "desc3(z, page_table_base)"
R1 = "extz(0b0, 64)"
R2 = "extz(page(x), 64)"
R3 = "x"

"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[final]
expect = "sat"
assertion = "1:X1=1 & 1:X3=0 & 2:X3=0"
