arch = "AArch64"
name = "W+T"
symbolic = ["x"]

page_table_setup = """
    physical pa1;
    x |-> pa1;
    x ?-> invalid at level 2;

    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
"""

[thread.0.reset]
R0 = "extz(0b0, 64)"
R1 = "pte2(x, page_table_base)"
"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[thread.1]
init = {}
code = """
    LDR X0,[X1]
"""

[thread.1.reset]
R1 = "x"
"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"
VBAR_EL1 = "extz(0x1000, 64)"

[section.handler]
address = "0x1000"
code = """
    MOV X0,#0
"""


[final]
assertion = "true"