arch = "AArch64"
name = "WRC.TTTf.inv+addrs"
symbolic = ["x", "y"]

page_table_setup = """
    physical pa1 pa2;
    x |-> invalid;
    x ?-> pa1;

    y |-> invalid;
    y ?-> pa2;

    *pa1 = 1;
    *pa2 = 1;

    identity 0x1000 with code;
    identity 0x2000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
"""

[thread.0.reset]
R0 = "mkdesc3(oa=pa1)"
R1 = "pte3(x, page_table_base)"

"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[thread.1]
init = {}
code = """
    MOV X0,#0
    LDR X0,[X1]
    EOR X4,X0,X0
    STR X2,[X3,X4]
"""

[thread.1.reset]
R1 = "x"
R2 = "mkdesc3(oa=pa2)"
R3 = "pte3(y, page_table_base)"

VBAR_EL1 = "extz(0x1000, 64)"
"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

"__isla_monomorphize_writes" = "true"

[section.thread1_el1_handler]
address = "0x1400"
code = """
    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[thread.2]
init = {}
code = """
    MOV X0,#0
    LDR X0,[X1]
    EOR X4,X0,X0
    MOV X2,#0
    LDR X2,[X3,X4]
"""

[thread.2.reset]
R1 = "y"
R3 = "x"

VBAR_EL1 = "extz(0x2000, 64)"
"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"

[section.thread2_el1_handler]
address = "0x2400"
code = """
    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[final]
assertion = "1:X0=1 & 2:X0=1 & 2:X2=0"