arch = "AArch64"
name = "WRC.TfRR+po+dsb"
symbolic = ["x", "y", "z"]

page_table_setup = """
    physical pa1 pa2;
    x |-> pa1;
    x ?-> invalid;

    *pa1 = 0;

    y |-> pa2;

    identity 0x1000 with code;
"""

[thread.0]
init = {}
code = """
    STR X0,[X1]
"""

[thread.0.reset]
R0 = "desc3(z, page_table_base)"
R1 = "pte3(x, page_table_base)"

"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[thread.1]
init = {}
code = """
    LDR X0,[X1]
    STR X2,[X3]
"""

[thread.1.reset]
R1 = "x"
R2 = "extz(0b1, 64)"
R3 = "y"

VBAR_EL1 = "extz(0x1000, 64)"
"PSTATE.EL" = "0b00"
"PSTATE.SP" = "0b0"

[section.thread1_el1_handler]
address = "0x1400"
code = """
    MOV X0,#1

    MRS X13,ELR_EL1
    ADD X13,X13,#4
    MSR ELR_EL1,X13
    ERET
"""

[thread.2]
init = {}
code = """
    LDR X0,[X1]
    DSB SY
    LDR X2,[X3]
"""

[thread.2.reset]
R1 = "y"
R3 = "pte3(x, page_table_base)"

"PSTATE.SP" = "0b0"
"PSTATE.EL" = "0b00"


[final]
assertion = "1:X0=1 & 2:X0=1 & ~2:X2=0"