arch = "AArch64"
name = "pKVM.switch_to_new_table"
symbolic = ["x"]

page_table_setup = """
option default_tables = false;
physical pa1;

s1table hyp_pgtable 0x200000  {
    x |-> invalid at level 3;
    x ?-> pa1;
    identity 0x2000 with code;
}

s1table new_hyp_pgtable 0x240000  {
    x |-> pa1 at level 3;
    x ?-> invalid;
    identity 0x2000 with code;
}

*pa1 = 1;
"""

[thread.0]
code = """
    MRS X2,SCTLR_EL2 // hyp-init.S:247
    BIC X3,X2,#1
    MSR SCTLR_EL2,X3
    ISB

    TLBI ALLE2

    MSR TTBR0_EL2,X4

    MSR SCTLR_EL2,X2
    ISB
    LDR X5,[X6]
"""

[thread.0.reset]
R4 = "ttbr(asid=0x0000, base=new_hyp_pgtable)"
R6 = "x"

TTBR0_EL2 = "ttbr(asid=0x0000, base=hyp_pgtable)"
VBAR_EL2 = "extz(0x2000, 64)"
"PSTATE.EL" = "0b10"
"PSTATE.SP" = "0b1"

[section.thread0_el2_handler]
address = "0x2200"
code = """
    MOV X5,#0
"""

[final]
assertion = "0:X2 = 0"

[graph]
force_show_events = [
    "T0:8:s1l3",
]
shows = [
    "iio",
    "po",
    "rf",
    "trf",
]
